### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by yuyuan871111** [ZFTurbo/segmentation_models_pytorch_3d#1]
https://github.com/ZFTurbo/segmentation_models_pytorch_3d/blob/66f0714c62b5f9adbae080ac10cec7fad565a2d4/segmentation_models_pytorch_3d/encoders/__init__.py#L1

I think there might be  ```import time```.

**Comment by ZFTurbo** [comment]
No it's really `timm`, but later I will replace it with `timm_3d`

**Comment by yuyuan871111** [comment]
I just found it!! Thank you!
