### ISSUE TITLE
problem pip install 

### ISSUE THREAD

**Issue by aysegulsayineker** [ZFTurbo/segmentation_models_pytorch_3d#4]
When you run the command pip install segmentation_models_pytorch_3d, you always receive an error:

ERROR: Could not find a version that satisfies the requirement segmentation_models_pytorch_3d (from versions: none)
ERROR: No matching distribution found for segmentation_models_pytorch_3d

**Comment by ZFTurbo** [comment]
What's your python version?

**Comment by ZFTurbo** [comment]
Sorry I think it's incorrect in readme. Try:

`pip install segmentation-models-pytorch-3d`
